version: "3.6"
services:
  firestore:
    build:
      context: .
      dockerfile: services/firestore/Dockerfile
    environment:
      PORT: 8812
  externalbroker:
    build:
      context: .
      dockerfile: services/broker/externalbroker/Dockerfile
    environment:
      PORT: 8081
      FIRESTORE_EMULATOR_HOST: firestore:8812
      USE_MOCK_ALLOCATOR: 1
    ports:
      - 8081:8081
  internalbroker:
    build:
      context: .
      dockerfile: services/broker/internalbroker/Dockerfile
    environment:
      PORT: 50501
      FIRESTORE_EMULATOR_HOST: firestore:8812
  ayame:
    build: ./services/ayame
    ports:
    - 3000:3000
  gameagent:
    build:
      context: .
      dockerfile: services/gaming/gameagent/Dockerfile
    environment:
      AYAME_LABO_URL: wss://ayame-labo.shiguredo.jp/signaling
      INTERNAL_BROKER_ADDR: internalbroker:50501
      GAME_WRAPPER_ADDR: game:50501
      PULSE_ADDR: localhost:4713
      USE_MOCK_ALLOCATOR: 1
      DISPLAY: ":0"
    env_file:
      - .env
    volumes:
      - x11socket:/tmp/.X11-unix/
    restart: always
  game:
    build:
      context: .
      dockerfile: services/gaming/game/Dockerfile
    environment:
      DISPLAY: ":0"
      PORT: 50501
      PULSE_SERVER: gameagent:4713
    security_opt:
      - seccomp:unconfined # to avoid clock_getres() failure with EPERM on i386 pulseaudio + macOS
    volumes:
      - ./games:/games
      - x11socket:/tmp/.X11-unix/
    restart: always
  pulseaudio:
    depends_on:
      - gameagent
    build: ./services/gaming/pulseaudio
    network_mode: service:gameagent
    restart: always

volumes:
  x11socket: