version: "3.6"
services:
  broker:
    build:
      context: .
      dockerfile: services/broker/Dockerfile
    environment:
      PORT: 8081
      INTERNAL_PORT: 50501
  ayame:
    build: ./services/ayame
    ports:
    - 3000:3000
  signaling:
    build:
      context: .
      dockerfile: services/signaling/Dockerfile
    environment:
      GAMESERVER_ADDR: "gameagent:12345"
      PORT: 8082
      INTERNAL_PORT: 50502
    ports:
      - 8082:8082
  gameagent:
    build:
      context: .
      dockerfile: services/gaming/gameagent/Dockerfile
    environment:
      BROKER_ADDR: broker:50501
      SIGNALING_ADDR: signaling:50502
    volumes:
      - x11socket:/tmp/.X11-unix/
  game:
    command: wine /microkiri/microkiri.exe
    build: ./services/gaming/game
    environment: 
      PULSE_SERVER: localhost:4713
    security_opt:
      - seccomp:unconfined # to avoid clock_getres() failure with EPERM on i386 pulseaudio
    volumes:
      - ./game/microkiri:/microkiri
      - x11socket:/tmp/.X11-unix/
    network_mode: service:gameagent

volumes:
  x11socket: