version: "3.6"
services:
  broker:
    build:
      context: .
      dockerfile: services/broker/Dockerfile
    environment:
      EXTERNAL_PORT: 8081
      INTERNAL_PORT: 50501
      USE_MOCK_ALLOCATOR: 1
    ports:
    - 8081:8081
  ayame:
    build: ./services/ayame
    ports:
    - 3000:3000
  gameagent:
    build:
      context: .
      dockerfile: services/gaming/gameagent/Dockerfile
    environment:
      INTERNAL_BROKER_ADDR: broker:50501
      AYAME_ADDR: ws://ayame:3000/signaling
      GAME_WRAPPER_ADDR: game:50501
      PULSE_ADDR: localhost:4713
      USE_MOCK_ALLOCATOR: 1
      DISPLAY: ":0"
    volumes:
      - x11socket:/tmp/.X11-unix/
  game:
    build:
      context: .
      dockerfile: services/gaming/game/Dockerfile
    environment:
      DISPLAY: ":0"
      PORT: 50501
      PULSE_SERVER: gameagent:4713
    volumes:
      - ./game/microkiri:/microkiri
      - x11socket:/tmp/.X11-unix/
  pulseaudio:
    depends_on:
      - gameagent
    build: ./services/gaming/pulseaudio
    security_opt:
      - seccomp:unconfined # to avoid clock_getres() failure with EPERM on i386 pulseaudio
    network_mode: service:gameagent

volumes:
  x11socket: