version: "3.6"
services:
  broker:
    build:
      context: .
      dockerfile: services/broker/Dockerfile
    environment:
      PORT: 8081
      INTERNAL_PORT: 50501
      GAMESERVER_ADDR: dummy
    ports:
    - 8081:8081
  ayame:
    build: ./services/ayame
    ports:
    - 3000:3000
  gameagent:
    build:
      context: .
      dockerfile: services/gaming/gameagent/Dockerfile
    environment:
      BROKER_ADDR: broker:50501
      AYAME_URL: ws://ayame:3000/signaling
      GAMEWRAPPER_ADDR: game:50501
      PULSE_ADDR: localhost:4713
    volumes:
      - x11socket:/tmp/.X11-unix/
  pulseaudio:
    build: ./services/gaming/pulseaudio
    security_opt:
      - seccomp:unconfined # to avoid clock_getres() failure with EPERM on i386 pulseaudio
    network_mode: service:gameagent
  xserver:
    build: ./services/gaming/xserver
    environment:
      DISPLAY: ":0"
    volumes:
      - x11socket:/tmp/.X11-unix/
  game:
    build:
      context: .
      dockerfile: services/gaming/game/Dockerfile
    environment:
      PORT: 50501
      PULSE_SERVER: pulseaudio:4713
    volumes:
      - ./game/microkiri:/microkiri
      - x11socket:/tmp/.X11-unix/

volumes:
  x11socket: