version: "3.6"
services:
  firestore:
    build:
      context: .
      dockerfile: services/firestore/Dockerfile
    environment:
      PORT: 8812
  externalbroker:
    build:
      context: .
      dockerfile: services/broker/externalbroker/Dockerfile
    environment:
      PORT: 8081
      FIRESTORE_EMULATOR_HOST: firestore:8812
      USE_MOCK_ALLOCATOR: 1
    ports:
      - 8081:8081
  internalbroker:
    build:
      context: .
      dockerfile: services/broker/internalbroker/Dockerfile
    environment:
      PORT: 50501
      FIRESTORE_EMULATOR_HOST: firestore:8812
  ayame:
    build: ./services/ayame
    ports:
    - 3000:3000
  gameserver:
    build:
      context: .
      dockerfile: services/gameserver/gameserver/Dockerfile
    environment:
      AYAME_LABO_URL: wss://ayame-labo.shiguredo.jp/signaling
      INTERNAL_BROKER_ADDR: internalbroker:50501
      GAME_PROCESS_ADDR: gameprocess:50501
      STREAMER_HOST: streamer
      STREAMER_ADDR: streamer:50502
      PULSE_ADDR: localhost:4713
      USE_MOCK_ALLOCATOR: 1
      DISPLAY: ":0"
    env_file:
      - .env
    volumes:
      - x11socket:/tmp/.X11-unix/
    restart: always
  gameprocess:
    build:
      context: .
      dockerfile: services/gameserver/gameprocess/Dockerfile
    environment:
      DISPLAY: ":0"
      PORT: 50501
      PULSE_SERVER: streamer:4713
    security_opt:
      - seccomp:unconfined # to avoid clock_getres() failure with EPERM on i386 pulseaudio + macOS
    volumes:
      - ./games/microkiri:/games/microkiri
      - x11socket:/tmp/.X11-unix/
      - appconfig:/var/run/appconfig
    ipc: host
    restart: always
  streamer:
    build:
      context: .
      dockerfile: services/gameserver/streamer/Dockerfile
    environment:
      DISPLAY: ":0"
      PORT: 50502
      GST_DEBUG: "default:4"
    volumes:
      - x11socket:/tmp/.X11-unix/
      - appconfig:/var/run/appconfig
    restart: always
    ipc: host
  pulseaudio:
    build: services/gameserver/pulseaudio
    network_mode: service:streamer
    restart: always
  xserver:
    build: services/gameserver/xserver
    ports:
      - 5900:5900
    environment:
      DISPLAY: ":0"
    volumes:
      - x11socket:/tmp/.X11-unix/
      - appconfig:/var/run/appconfig
    ipc: host

volumes:
  x11socket:
  appconfig: