resources:
  - services/broker/externalbroker/externalbroker.yaml
  - services/broker/internalbroker/internalbroker.yaml
  - services/fleet.yaml
namespace: mashimaro
secretGenerator:
  - name: ayame-labo-secrets
    envs:
      - .env
generatorOptions:
  disableNameSuffixHash: true # Agones fleet containers spec does not respond suffix hash...
