apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: mashimaro/externalbroker
      context: .
      docker:
        dockerfile: services/broker/externalbroker/Dockerfile
    - image: mashimaro/internalbroker
      context: .
      docker:
        dockerfile: services/broker/internalbroker/Dockerfile
    - image: mashimaro/gameserver
      context: .
      docker:
        dockerfile: services/gameserver/gameserver/Dockerfile
    - image: mashimaro/game
      context: .
      docker:
        dockerfile: services/gameserver/gameprocess/Dockerfile
    - image: mashimaro/pulseaudio
      context: services/gameserver/pulseaudio
      docker:
        dockerfile: Dockerfile
    - image: mashimaro/firestore
      context: .
      docker:
        dockerfile: services/firestore/Dockerfile
  local:
    useBuildkit: true
deploy:
  kustomize:
    paths:
      - "."
