apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: mashimaro/broker
      context: .
      docker:
        dockerfile: services/broker/Dockerfile
    - image: mashimaro/gameagent
      context: .
      docker:
        dockerfile: services/gaming/gameagent/Dockerfile
    - image: mashimaro/game
      context: .
      docker:
        dockerfile: services/gaming/game/Dockerfile
    - image: mashimaro/pulseaudio
      context: services/gaming/pulseaudio
      docker:
        dockerfile: Dockerfile
  local:
    useBuildkit: true
deploy:
  kustomize:
    paths:
      - "."
