---
kind: Pod
apiVersion: v1
metadata:
  name: externalbroker
  labels:
    component: externalbroker
spec:
  containers:
    - name: externalbroker
      image: mashimaro/externalbroker
      imagePullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: 8081
      env:
        - name: PORT
          value: "8081"
        - name: ALLOCATOR_ADDR
          value: agones-allocator.agones-system.svc.cluster.local.:443
        - name: FLEET_NAMESPACE
          value: mashimaro
---
kind: Service
apiVersion: v1
metadata:
  name: externalbroker
  labels:
    component: externalbroker
spec:
  selector:
    component: externalbroker
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
