---
kind: Pod
apiVersion: v1
metadata:
  name: internalbroker
  labels:
    component: internalbroker
spec:
  containers:
    - name: internalbroker
      image: mashimaro/internalbroker
      imagePullPolicy: IfNotPresent
      ports:
        - name: grpc
          containerPort: 50501
      env:
        - name: PORT
          value: "50501"
        - name: FIRESTORE_EMULATOR_HOST
          value: firestore.mashimaro.svc.cluster.local.:8812
---
kind: Service
apiVersion: v1
metadata:
  name: internalbroker
  labels:
    component: internalbroker
spec:
  clusterIP: None
  selector:
    component: internalbroker