apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: mashimaro-fleet
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    spec:
      container: gameserver
      ports:
        - name: dummy
          containerPort: 12345
          protocol: TCP
      template:
        spec:
          volumes:
            - name: games
              hostPath:
                path: /games
            - name: x11
              emptyDir:
                medium: Memory
                sizeLimit: 10Mi
          containers:
            - name: gameserver
              image: mashimaro/gameserver
              env:
                - name: AYAME_LABO_URL
                  value: wss://ayame-labo.shiguredo.jp/signaling
                - name: AYAME_LABO_SIGNALING_KEY
                  valueFrom:
                    secretKeyRef:
                      name: ayame-labo-secrets
                      key: AYAME_LABO_SIGNALING_KEY
                - name: AYAME_LABO_GITHUB_ACCOUNT
                  valueFrom:
                    secretKeyRef:
                      name: ayame-labo-secrets
                      key: AYAME_LABO_GITHUB_ACCOUNT
                - name: INTERNAL_BROKER_ADDR
                  value: internalbroker.mashimaro.svc.cluster.local.:50501
                - name: GAME_PROCESS_ADDR
                  value: localhost:50501
                - name: PULSE_SERVER
                  value: localhost:4713
                - name: DISPLAY
                  value: ":0"
              volumeMounts:
                - name: x11
                  mountPath: /tmp/.X11-unix
            - name: game
              image: mashimaro/game
              env:
                - name: PORT
                  value: "50501"
                - name: PULSE_SERVER
                  value: localhost:4713
              volumeMounts:
                - name: x11
                  mountPath: /tmp/.X11-unix
                - name: games
                  mountPath: /games
            - name: pulseaudio
              image: mashimaro/pulseaudio
