apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: mashimaro-fleet
  namespace: mashimaro
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    spec:
      container: gameagent
      ports:
        - name: dummy
          containerPort: 12345
          protocol: TCP
      template:
        spec:
          containers:
            - name: gameagent
              image: mashimaro/gameagent
              env:
                - name: AYAME_URL
                  value: ws://ayame.mashimaro.svc.cluster.local.:3000/signal"
            - name: game
              image: mashimaro/game
              env:
                - name: PORT
                  value: "50501"
                - name: PULSE_SERVER
                  value: localhost:4713
            - name: pulseaudio
              image: mashimaro/pulseaudio
            - name: xserver
              image: mashimaro/xserver
              env:
                - name: DISPLAY
                  value: ":0"
