---
kind: Pod
apiVersion: v1
metadata:
  name: broker
  labels:
    component: broker
spec:
  containers:
    - name: broker
      image: mashimaro/broker
      imagePullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: 8081
      env:
        - name: EXTERNAL_PORT
          value: "8081"
        - name: INTERNAL_PORT
          value: "50501"
        - name: ALLOCATOR_ADDR
          value: agones-allocator.agones-system.svc.cluster.local.:443
        - name: FLEET_NAMESPACE
          value: mashimaro
---
kind: Service
apiVersion: v1
metadata:
  name: broker
  labels:
    component: broker
spec:
  selector:
    component: broker
  ports:
    - name: external
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: internal
      protocol: TCP
      port: 50501
      targetPort: 50501
