// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/broker.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	proto/broker.proto
	proto/encoder.proto
	proto/gameprocess.proto

It has these top-level messages:
	FindSessionRequest
	FindSessionResponse
	DeleteSessionRequest
	DeleteSessionResponse
	Session
	GetGameMetadataRequest
	GetGameMetadataResponse
	GameMetadata
	StartEncodingRequest
	StartEncodingResponse
	StartGameRequest
	StartGameResponse
	ExitGameRequest
	ExitGameResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type FindSessionRequest struct {
	AllocatedServerId string `protobuf:"bytes,1,opt,name=allocated_server_id,json=allocatedServerId" json:"allocated_server_id,omitempty"`
}

func (m *FindSessionRequest) Reset()                    { *m = FindSessionRequest{} }
func (m *FindSessionRequest) String() string            { return proto1.CompactTextString(m) }
func (*FindSessionRequest) ProtoMessage()               {}
func (*FindSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FindSessionRequest) GetAllocatedServerId() string {
	if m != nil {
		return m.AllocatedServerId
	}
	return ""
}

type FindSessionResponse struct {
	Found   bool     `protobuf:"varint,1,opt,name=found" json:"found,omitempty"`
	Session *Session `protobuf:"bytes,2,opt,name=session" json:"session,omitempty"`
}

func (m *FindSessionResponse) Reset()                    { *m = FindSessionResponse{} }
func (m *FindSessionResponse) String() string            { return proto1.CompactTextString(m) }
func (*FindSessionResponse) ProtoMessage()               {}
func (*FindSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FindSessionResponse) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

func (m *FindSessionResponse) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type DeleteSessionRequest struct {
	SessionId         string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	AllocatedServerId string `protobuf:"bytes,2,opt,name=allocated_server_id,json=allocatedServerId" json:"allocated_server_id,omitempty"`
}

func (m *DeleteSessionRequest) Reset()                    { *m = DeleteSessionRequest{} }
func (m *DeleteSessionRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteSessionRequest) ProtoMessage()               {}
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeleteSessionRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *DeleteSessionRequest) GetAllocatedServerId() string {
	if m != nil {
		return m.AllocatedServerId
	}
	return ""
}

type DeleteSessionResponse struct {
}

func (m *DeleteSessionResponse) Reset()                    { *m = DeleteSessionResponse{} }
func (m *DeleteSessionResponse) String() string            { return proto1.CompactTextString(m) }
func (*DeleteSessionResponse) ProtoMessage()               {}
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Session struct {
	SessionId         string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	AllocatedServerId string `protobuf:"bytes,2,opt,name=allocated_server_id,json=allocatedServerId" json:"allocated_server_id,omitempty"`
	GameId            string `protobuf:"bytes,3,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto1.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Session) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *Session) GetAllocatedServerId() string {
	if m != nil {
		return m.AllocatedServerId
	}
	return ""
}

func (m *Session) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

type GetGameMetadataRequest struct {
	GameId string `protobuf:"bytes,1,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
}

func (m *GetGameMetadataRequest) Reset()                    { *m = GetGameMetadataRequest{} }
func (m *GetGameMetadataRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetGameMetadataRequest) ProtoMessage()               {}
func (*GetGameMetadataRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetGameMetadataRequest) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

type GetGameMetadataResponse struct {
	GameMetadata *GameMetadata `protobuf:"bytes,1,opt,name=game_metadata,json=gameMetadata" json:"game_metadata,omitempty"`
}

func (m *GetGameMetadataResponse) Reset()                    { *m = GetGameMetadataResponse{} }
func (m *GetGameMetadataResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetGameMetadataResponse) ProtoMessage()               {}
func (*GetGameMetadataResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetGameMetadataResponse) GetGameMetadata() *GameMetadata {
	if m != nil {
		return m.GameMetadata
	}
	return nil
}

type GameMetadata struct {
	Body string `protobuf:"bytes,1,opt,name=body" json:"body,omitempty"`
}

func (m *GameMetadata) Reset()                    { *m = GameMetadata{} }
func (m *GameMetadata) String() string            { return proto1.CompactTextString(m) }
func (*GameMetadata) ProtoMessage()               {}
func (*GameMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GameMetadata) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto1.RegisterType((*FindSessionRequest)(nil), "FindSessionRequest")
	proto1.RegisterType((*FindSessionResponse)(nil), "FindSessionResponse")
	proto1.RegisterType((*DeleteSessionRequest)(nil), "DeleteSessionRequest")
	proto1.RegisterType((*DeleteSessionResponse)(nil), "DeleteSessionResponse")
	proto1.RegisterType((*Session)(nil), "Session")
	proto1.RegisterType((*GetGameMetadataRequest)(nil), "GetGameMetadataRequest")
	proto1.RegisterType((*GetGameMetadataResponse)(nil), "GetGameMetadataResponse")
	proto1.RegisterType((*GameMetadata)(nil), "GameMetadata")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Broker service

type BrokerClient interface {
	FindSession(ctx context.Context, in *FindSessionRequest, opts ...grpc.CallOption) (*FindSessionResponse, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
	GetGameMetadata(ctx context.Context, in *GetGameMetadataRequest, opts ...grpc.CallOption) (*GetGameMetadataResponse, error)
}

type brokerClient struct {
	cc *grpc.ClientConn
}

func NewBrokerClient(cc *grpc.ClientConn) BrokerClient {
	return &brokerClient{cc}
}

func (c *brokerClient) FindSession(ctx context.Context, in *FindSessionRequest, opts ...grpc.CallOption) (*FindSessionResponse, error) {
	out := new(FindSessionResponse)
	err := grpc.Invoke(ctx, "/Broker/FindSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	out := new(DeleteSessionResponse)
	err := grpc.Invoke(ctx, "/Broker/DeleteSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) GetGameMetadata(ctx context.Context, in *GetGameMetadataRequest, opts ...grpc.CallOption) (*GetGameMetadataResponse, error) {
	out := new(GetGameMetadataResponse)
	err := grpc.Invoke(ctx, "/Broker/GetGameMetadata", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Broker service

type BrokerServer interface {
	FindSession(context.Context, *FindSessionRequest) (*FindSessionResponse, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
	GetGameMetadata(context.Context, *GetGameMetadataRequest) (*GetGameMetadataResponse, error)
}

func RegisterBrokerServer(s *grpc.Server, srv BrokerServer) {
	s.RegisterService(&_Broker_serviceDesc, srv)
}

func _Broker_FindSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).FindSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Broker/FindSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).FindSession(ctx, req.(*FindSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Broker/DeleteSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_GetGameMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).GetGameMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Broker/GetGameMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).GetGameMetadata(ctx, req.(*GetGameMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Broker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Broker",
	HandlerType: (*BrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindSession",
			Handler:    _Broker_FindSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _Broker_DeleteSession_Handler,
		},
		{
			MethodName: "GetGameMetadata",
			Handler:    _Broker_GetGameMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/broker.proto",
}

func init() { proto1.RegisterFile("proto/broker.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0xa5, 0x28, 0x14, 0x06, 0x88, 0x71, 0xf8, 0x28, 0x21, 0x31, 0x21, 0x7b, 0xe2, 0xb4, 0xc6,
	0x7a, 0xf3, 0x64, 0x08, 0x81, 0x70, 0x20, 0x26, 0x70, 0xf3, 0x42, 0x16, 0x77, 0x24, 0x44, 0xe8,
	0x42, 0x77, 0x31, 0xf1, 0x4f, 0xfa, 0x9b, 0x0c, 0xdb, 0xa2, 0x2d, 0x94, 0x9b, 0xa7, 0x76, 0xf6,
	0xbd, 0xd7, 0x79, 0xfb, 0x66, 0x0a, 0xb8, 0x0d, 0x95, 0x51, 0xf7, 0x8b, 0x50, 0x7d, 0x50, 0xc8,
	0x6d, 0xc1, 0x06, 0x80, 0xc3, 0x55, 0x20, 0x67, 0xa4, 0xf5, 0x4a, 0x05, 0x53, 0xda, 0xed, 0x49,
	0x1b, 0xe4, 0x50, 0x17, 0xeb, 0xb5, 0x7a, 0x13, 0x86, 0xe4, 0x5c, 0x53, 0xf8, 0x49, 0xe1, 0x7c,
	0x25, 0xdb, 0x4e, 0xd7, 0xe9, 0x95, 0xa7, 0xb7, 0xbf, 0xd0, 0xcc, 0x22, 0x63, 0xc9, 0x5e, 0xa0,
	0x9e, 0xfa, 0x8a, 0xde, 0xaa, 0x40, 0x13, 0x36, 0xa0, 0xf0, 0xae, 0xf6, 0x41, 0x24, 0x2c, 0x4d,
	0xa3, 0x02, 0x19, 0xb8, 0x3a, 0x22, 0xb6, 0xf3, 0x5d, 0xa7, 0x57, 0xf1, 0x4b, 0xfc, 0x28, 0x3c,
	0x02, 0x8c, 0xa0, 0x31, 0xa0, 0x35, 0x19, 0x3a, 0x31, 0x76, 0x07, 0x10, 0x53, 0xfe, 0xfc, 0x94,
	0xe3, 0x93, 0xb1, 0xbc, 0xe4, 0x3b, 0x7f, 0xc9, 0xb7, 0x07, 0xcd, 0x93, 0x36, 0x91, 0x73, 0xb6,
	0x03, 0x37, 0x3e, 0xfa, 0xe7, 0x96, 0xe8, 0x81, 0xbb, 0x14, 0x1b, 0x3a, 0x70, 0xae, 0x2c, 0xa7,
	0x78, 0x28, 0xc7, 0x92, 0x3d, 0x40, 0x6b, 0x44, 0x66, 0x24, 0x36, 0x34, 0x21, 0x23, 0xa4, 0x30,
	0xe2, 0x78, 0xe9, 0x84, 0xc4, 0x49, 0x49, 0x26, 0xe0, 0x9d, 0x49, 0xe2, 0xe8, 0x7d, 0xa8, 0x59,
	0xcd, 0x26, 0x06, 0xac, 0xb2, 0xe2, 0xd7, 0x78, 0x8a, 0x5d, 0x5d, 0x26, 0x2a, 0xc6, 0xa0, 0x9a,
	0x44, 0x11, 0xe1, 0x7a, 0xa1, 0xe4, 0x57, 0xdc, 0xd4, 0xbe, 0xfb, 0xdf, 0x0e, 0x14, 0xfb, 0x76,
	0x81, 0xf0, 0x09, 0x2a, 0x89, 0xa1, 0x63, 0x9d, 0x9f, 0x2f, 0x52, 0xa7, 0xc1, 0x33, 0xf6, 0x82,
	0xe5, 0xf0, 0x19, 0x6a, 0xa9, 0xe0, 0xb1, 0xc9, 0xb3, 0xe6, 0xdd, 0x69, 0xf1, 0xec, 0xf9, 0xe4,
	0x70, 0x08, 0x37, 0x27, 0x77, 0x47, 0x8f, 0x67, 0x07, 0xd8, 0x69, 0xf3, 0x0b, 0x31, 0xb1, 0x5c,
	0xdf, 0x7d, 0x2d, 0xd8, 0x3f, 0x61, 0x51, 0xb4, 0x8f, 0xc7, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xb3, 0xb8, 0x6f, 0x57, 0x26, 0x03, 0x00, 0x00,
}
