// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/gamewrapper.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type StartGameRequest struct {
	Command          string   `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	Args             []string `protobuf:"bytes,2,rep,name=args" json:"args,omitempty"`
	WorkingDirectory string   `protobuf:"bytes,3,opt,name=working_directory,json=workingDirectory" json:"working_directory,omitempty"`
}

func (m *StartGameRequest) Reset()                    { *m = StartGameRequest{} }
func (m *StartGameRequest) String() string            { return proto1.CompactTextString(m) }
func (*StartGameRequest) ProtoMessage()               {}
func (*StartGameRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *StartGameRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *StartGameRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *StartGameRequest) GetWorkingDirectory() string {
	if m != nil {
		return m.WorkingDirectory
	}
	return ""
}

type StartGameResponse struct {
}

func (m *StartGameResponse) Reset()                    { *m = StartGameResponse{} }
func (m *StartGameResponse) String() string            { return proto1.CompactTextString(m) }
func (*StartGameResponse) ProtoMessage()               {}
func (*StartGameResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type ExitGameRequest struct {
}

func (m *ExitGameRequest) Reset()                    { *m = ExitGameRequest{} }
func (m *ExitGameRequest) String() string            { return proto1.CompactTextString(m) }
func (*ExitGameRequest) ProtoMessage()               {}
func (*ExitGameRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type ExitGameResponse struct {
}

func (m *ExitGameResponse) Reset()                    { *m = ExitGameResponse{} }
func (m *ExitGameResponse) String() string            { return proto1.CompactTextString(m) }
func (*ExitGameResponse) ProtoMessage()               {}
func (*ExitGameResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

type HealthCheckRequest struct {
}

func (m *HealthCheckRequest) Reset()                    { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string            { return proto1.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()               {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type HealthCheckResponse struct {
	Healthy bool `protobuf:"varint,1,opt,name=healthy" json:"healthy,omitempty"`
}

func (m *HealthCheckResponse) Reset()                    { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string            { return proto1.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()               {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *HealthCheckResponse) GetHealthy() bool {
	if m != nil {
		return m.Healthy
	}
	return false
}

func init() {
	proto1.RegisterType((*StartGameRequest)(nil), "StartGameRequest")
	proto1.RegisterType((*StartGameResponse)(nil), "StartGameResponse")
	proto1.RegisterType((*ExitGameRequest)(nil), "ExitGameRequest")
	proto1.RegisterType((*ExitGameResponse)(nil), "ExitGameResponse")
	proto1.RegisterType((*HealthCheckRequest)(nil), "HealthCheckRequest")
	proto1.RegisterType((*HealthCheckResponse)(nil), "HealthCheckResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GameWrapper service

type GameWrapperClient interface {
	StartGame(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*StartGameResponse, error)
	ExitGame(ctx context.Context, in *ExitGameRequest, opts ...grpc.CallOption) (*ExitGameResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type gameWrapperClient struct {
	cc *grpc.ClientConn
}

func NewGameWrapperClient(cc *grpc.ClientConn) GameWrapperClient {
	return &gameWrapperClient{cc}
}

func (c *gameWrapperClient) StartGame(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*StartGameResponse, error) {
	out := new(StartGameResponse)
	err := grpc.Invoke(ctx, "/GameWrapper/StartGame", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameWrapperClient) ExitGame(ctx context.Context, in *ExitGameRequest, opts ...grpc.CallOption) (*ExitGameResponse, error) {
	out := new(ExitGameResponse)
	err := grpc.Invoke(ctx, "/GameWrapper/ExitGame", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameWrapperClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := grpc.Invoke(ctx, "/GameWrapper/HealthCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GameWrapper service

type GameWrapperServer interface {
	StartGame(context.Context, *StartGameRequest) (*StartGameResponse, error)
	ExitGame(context.Context, *ExitGameRequest) (*ExitGameResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
}

func RegisterGameWrapperServer(s *grpc.Server, srv GameWrapperServer) {
	s.RegisterService(&_GameWrapper_serviceDesc, srv)
}

func _GameWrapper_StartGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameWrapperServer).StartGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GameWrapper/StartGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameWrapperServer).StartGame(ctx, req.(*StartGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameWrapper_ExitGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExitGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameWrapperServer).ExitGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GameWrapper/ExitGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameWrapperServer).ExitGame(ctx, req.(*ExitGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameWrapper_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameWrapperServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GameWrapper/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameWrapperServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GameWrapper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GameWrapper",
	HandlerType: (*GameWrapperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartGame",
			Handler:    _GameWrapper_StartGame_Handler,
		},
		{
			MethodName: "ExitGame",
			Handler:    _GameWrapper_ExitGame_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _GameWrapper_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gamewrapper.proto",
}

func init() { proto1.RegisterFile("proto/gamewrapper.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x13, 0x0a, 0xb4, 0xb9, 0x0e, 0xc4, 0x97, 0x4a, 0x44, 0x99, 0x2a, 0x4f, 0x95, 0x90,
	0x5c, 0xf1, 0x67, 0x62, 0xe4, 0x8f, 0x60, 0x0e, 0x03, 0x12, 0x0b, 0x32, 0xa9, 0x95, 0x44, 0xc5,
	0x71, 0x70, 0x8c, 0x4a, 0xbf, 0x16, 0x9f, 0x10, 0xd5, 0xad, 0x21, 0x24, 0x9d, 0xec, 0x7b, 0x7e,
	0xb6, 0x7f, 0xef, 0x0e, 0x4e, 0x6b, 0xad, 0x8c, 0x9a, 0xe7, 0x5c, 0x8a, 0x95, 0xe6, 0x75, 0x2d,
	0x34, 0xb3, 0x0a, 0x95, 0x10, 0x3e, 0x19, 0xae, 0xcd, 0x03, 0x97, 0x22, 0x15, 0x1f, 0x9f, 0xa2,
	0x31, 0x18, 0xc3, 0x30, 0x53, 0x52, 0xf2, 0x6a, 0x11, 0xfb, 0x53, 0x7f, 0x16, 0xa4, 0xae, 0x44,
	0x84, 0x43, 0xae, 0xf3, 0x26, 0x3e, 0x98, 0x0e, 0x66, 0x41, 0x6a, 0xf7, 0x78, 0x06, 0x64, 0xa5,
	0xf4, 0xb2, 0xac, 0xf2, 0xd7, 0x45, 0xa9, 0x45, 0x66, 0x94, 0x5e, 0xc7, 0x03, 0x7b, 0x2f, 0xdc,
	0x1d, 0xdc, 0x39, 0x9d, 0x46, 0x40, 0x5a, 0xdf, 0x35, 0xb5, 0xaa, 0x1a, 0x41, 0x09, 0x9c, 0xdc,
	0x7f, 0x95, 0x6d, 0x04, 0x8a, 0x10, 0xfe, 0x49, 0x3b, 0xdb, 0x04, 0xf0, 0x51, 0xf0, 0x77, 0x53,
	0xdc, 0x16, 0x22, 0x5b, 0x3a, 0xe7, 0x1c, 0xa2, 0x7f, 0xea, 0xd6, 0xbc, 0xc9, 0x50, 0x58, 0x79,
	0x6d, 0x33, 0x8c, 0x52, 0x57, 0x5e, 0x7c, 0xfb, 0x30, 0xde, 0xbc, 0xfb, 0xbc, 0xed, 0x03, 0x5e,
	0x41, 0xf0, 0x8b, 0x84, 0x84, 0x75, 0xbb, 0x91, 0x20, 0xeb, 0x13, 0x7b, 0x78, 0x0e, 0x23, 0x07,
	0x88, 0x21, 0xeb, 0xe0, 0x27, 0x84, 0xf5, 0xe8, 0x3d, 0xbc, 0x86, 0x71, 0x8b, 0x14, 0x23, 0xd6,
	0x4f, 0x93, 0x4c, 0xd8, 0x9e, 0x30, 0xd4, 0xbb, 0x19, 0xbe, 0x1c, 0xd9, 0x79, 0xbd, 0x1d, 0xdb,
	0xe5, 0xf2, 0x27, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x0d, 0xec, 0x3d, 0xd1, 0x01, 0x00, 0x00,
}
