// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/gamewrapper.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type StartGameRequest struct {
	Command          string   `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	Args             []string `protobuf:"bytes,2,rep,name=args" json:"args,omitempty"`
	WorkingDirectory string   `protobuf:"bytes,3,opt,name=working_directory,json=workingDirectory" json:"working_directory,omitempty"`
}

func (m *StartGameRequest) Reset()                    { *m = StartGameRequest{} }
func (m *StartGameRequest) String() string            { return proto1.CompactTextString(m) }
func (*StartGameRequest) ProtoMessage()               {}
func (*StartGameRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *StartGameRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *StartGameRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *StartGameRequest) GetWorkingDirectory() string {
	if m != nil {
		return m.WorkingDirectory
	}
	return ""
}

type StartGameResponse struct {
}

func (m *StartGameResponse) Reset()                    { *m = StartGameResponse{} }
func (m *StartGameResponse) String() string            { return proto1.CompactTextString(m) }
func (*StartGameResponse) ProtoMessage()               {}
func (*StartGameResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type ExitGameRequest struct {
}

func (m *ExitGameRequest) Reset()                    { *m = ExitGameRequest{} }
func (m *ExitGameRequest) String() string            { return proto1.CompactTextString(m) }
func (*ExitGameRequest) ProtoMessage()               {}
func (*ExitGameRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type ExitGameResponse struct {
}

func (m *ExitGameResponse) Reset()                    { *m = ExitGameResponse{} }
func (m *ExitGameResponse) String() string            { return proto1.CompactTextString(m) }
func (*ExitGameResponse) ProtoMessage()               {}
func (*ExitGameResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

type HealthCheckRequest struct {
}

func (m *HealthCheckRequest) Reset()                    { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string            { return proto1.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()               {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type HealthCheckResponse struct {
	Healthy bool `protobuf:"varint,1,opt,name=healthy" json:"healthy,omitempty"`
}

func (m *HealthCheckResponse) Reset()                    { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string            { return proto1.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()               {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *HealthCheckResponse) GetHealthy() bool {
	if m != nil {
		return m.Healthy
	}
	return false
}

type ListenCaptureAreaRequest struct {
}

func (m *ListenCaptureAreaRequest) Reset()                    { *m = ListenCaptureAreaRequest{} }
func (m *ListenCaptureAreaRequest) String() string            { return proto1.CompactTextString(m) }
func (*ListenCaptureAreaRequest) ProtoMessage()               {}
func (*ListenCaptureAreaRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

type ListenCaptureAreaResponse struct {
	StartX uint32 `protobuf:"varint,1,opt,name=start_x,json=startX" json:"start_x,omitempty"`
	StartY uint32 `protobuf:"varint,2,opt,name=start_y,json=startY" json:"start_y,omitempty"`
	EndX   uint32 `protobuf:"varint,3,opt,name=end_x,json=endX" json:"end_x,omitempty"`
	EndY   uint32 `protobuf:"varint,4,opt,name=end_y,json=endY" json:"end_y,omitempty"`
}

func (m *ListenCaptureAreaResponse) Reset()                    { *m = ListenCaptureAreaResponse{} }
func (m *ListenCaptureAreaResponse) String() string            { return proto1.CompactTextString(m) }
func (*ListenCaptureAreaResponse) ProtoMessage()               {}
func (*ListenCaptureAreaResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *ListenCaptureAreaResponse) GetStartX() uint32 {
	if m != nil {
		return m.StartX
	}
	return 0
}

func (m *ListenCaptureAreaResponse) GetStartY() uint32 {
	if m != nil {
		return m.StartY
	}
	return 0
}

func (m *ListenCaptureAreaResponse) GetEndX() uint32 {
	if m != nil {
		return m.EndX
	}
	return 0
}

func (m *ListenCaptureAreaResponse) GetEndY() uint32 {
	if m != nil {
		return m.EndY
	}
	return 0
}

func init() {
	proto1.RegisterType((*StartGameRequest)(nil), "StartGameRequest")
	proto1.RegisterType((*StartGameResponse)(nil), "StartGameResponse")
	proto1.RegisterType((*ExitGameRequest)(nil), "ExitGameRequest")
	proto1.RegisterType((*ExitGameResponse)(nil), "ExitGameResponse")
	proto1.RegisterType((*HealthCheckRequest)(nil), "HealthCheckRequest")
	proto1.RegisterType((*HealthCheckResponse)(nil), "HealthCheckResponse")
	proto1.RegisterType((*ListenCaptureAreaRequest)(nil), "ListenCaptureAreaRequest")
	proto1.RegisterType((*ListenCaptureAreaResponse)(nil), "ListenCaptureAreaResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GameWrapper service

type GameWrapperClient interface {
	StartGame(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*StartGameResponse, error)
	ExitGame(ctx context.Context, in *ExitGameRequest, opts ...grpc.CallOption) (*ExitGameResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	ListenCaptureArea(ctx context.Context, in *ListenCaptureAreaRequest, opts ...grpc.CallOption) (GameWrapper_ListenCaptureAreaClient, error)
}

type gameWrapperClient struct {
	cc *grpc.ClientConn
}

func NewGameWrapperClient(cc *grpc.ClientConn) GameWrapperClient {
	return &gameWrapperClient{cc}
}

func (c *gameWrapperClient) StartGame(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*StartGameResponse, error) {
	out := new(StartGameResponse)
	err := grpc.Invoke(ctx, "/GameWrapper/StartGame", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameWrapperClient) ExitGame(ctx context.Context, in *ExitGameRequest, opts ...grpc.CallOption) (*ExitGameResponse, error) {
	out := new(ExitGameResponse)
	err := grpc.Invoke(ctx, "/GameWrapper/ExitGame", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameWrapperClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := grpc.Invoke(ctx, "/GameWrapper/HealthCheck", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameWrapperClient) ListenCaptureArea(ctx context.Context, in *ListenCaptureAreaRequest, opts ...grpc.CallOption) (GameWrapper_ListenCaptureAreaClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GameWrapper_serviceDesc.Streams[0], c.cc, "/GameWrapper/ListenCaptureArea", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameWrapperListenCaptureAreaClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GameWrapper_ListenCaptureAreaClient interface {
	Recv() (*ListenCaptureAreaResponse, error)
	grpc.ClientStream
}

type gameWrapperListenCaptureAreaClient struct {
	grpc.ClientStream
}

func (x *gameWrapperListenCaptureAreaClient) Recv() (*ListenCaptureAreaResponse, error) {
	m := new(ListenCaptureAreaResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GameWrapper service

type GameWrapperServer interface {
	StartGame(context.Context, *StartGameRequest) (*StartGameResponse, error)
	ExitGame(context.Context, *ExitGameRequest) (*ExitGameResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	ListenCaptureArea(*ListenCaptureAreaRequest, GameWrapper_ListenCaptureAreaServer) error
}

func RegisterGameWrapperServer(s *grpc.Server, srv GameWrapperServer) {
	s.RegisterService(&_GameWrapper_serviceDesc, srv)
}

func _GameWrapper_StartGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameWrapperServer).StartGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GameWrapper/StartGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameWrapperServer).StartGame(ctx, req.(*StartGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameWrapper_ExitGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExitGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameWrapperServer).ExitGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GameWrapper/ExitGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameWrapperServer).ExitGame(ctx, req.(*ExitGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameWrapper_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameWrapperServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GameWrapper/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameWrapperServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameWrapper_ListenCaptureArea_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenCaptureAreaRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GameWrapperServer).ListenCaptureArea(m, &gameWrapperListenCaptureAreaServer{stream})
}

type GameWrapper_ListenCaptureAreaServer interface {
	Send(*ListenCaptureAreaResponse) error
	grpc.ServerStream
}

type gameWrapperListenCaptureAreaServer struct {
	grpc.ServerStream
}

func (x *gameWrapperListenCaptureAreaServer) Send(m *ListenCaptureAreaResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _GameWrapper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GameWrapper",
	HandlerType: (*GameWrapperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartGame",
			Handler:    _GameWrapper_StartGame_Handler,
		},
		{
			MethodName: "ExitGame",
			Handler:    _GameWrapper_ExitGame_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _GameWrapper_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListenCaptureArea",
			Handler:       _GameWrapper_ListenCaptureArea_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/gamewrapper.proto",
}

func init() { proto1.RegisterFile("proto/gamewrapper.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xbd, 0x6f, 0xf2, 0x30,
	0x10, 0xc6, 0xc3, 0x37, 0x1c, 0x42, 0x6f, 0x72, 0x41, 0x22, 0x64, 0x42, 0x99, 0x90, 0x5e, 0xc9,
	0xf4, 0x6b, 0xea, 0xd6, 0xd2, 0xaa, 0x1d, 0xaa, 0x0e, 0xe9, 0x50, 0xe8, 0x82, 0x5c, 0x62, 0x41,
	0x44, 0xf3, 0x51, 0xc7, 0x08, 0xb2, 0xf6, 0x2f, 0xaf, 0x30, 0x18, 0x52, 0x02, 0x53, 0x72, 0xcf,
	0x73, 0x3e, 0xdf, 0xfd, 0xce, 0xd0, 0x89, 0x79, 0x24, 0xa2, 0xc1, 0x8c, 0x06, 0x6c, 0xc5, 0x69,
	0x1c, 0x33, 0x4e, 0xa4, 0xe2, 0x04, 0xa0, 0xbf, 0x09, 0xca, 0xc5, 0x13, 0x0d, 0x98, 0xcb, 0xbe,
	0x97, 0x2c, 0x11, 0x68, 0x41, 0x6d, 0x1a, 0x05, 0x01, 0x0d, 0x3d, 0xab, 0xd0, 0x2b, 0xf4, 0x1b,
	0xae, 0x0a, 0x11, 0xa1, 0x4c, 0xf9, 0x2c, 0xb1, 0x8a, 0xbd, 0x52, 0xbf, 0xe1, 0xca, 0x7f, 0xfc,
	0x0f, 0xc6, 0x2a, 0xe2, 0x0b, 0x3f, 0x9c, 0x4d, 0x3c, 0x9f, 0xb3, 0xa9, 0x88, 0x78, 0x6a, 0x95,
	0xe4, 0x39, 0x7d, 0x67, 0x3c, 0x28, 0xdd, 0x31, 0xc1, 0xc8, 0x5c, 0x97, 0xc4, 0x51, 0x98, 0x30,
	0xc7, 0x80, 0x7f, 0x8f, 0x6b, 0x3f, 0xdb, 0x82, 0x83, 0xa0, 0x1f, 0xa4, 0x5d, 0x5a, 0x1b, 0xf0,
	0x99, 0xd1, 0x2f, 0x31, 0x1f, 0xce, 0xd9, 0x74, 0xa1, 0x32, 0x07, 0x60, 0xfe, 0x51, 0xb7, 0xc9,
	0x9b, 0x19, 0xe6, 0x52, 0x4e, 0xe5, 0x0c, 0x75, 0x57, 0x85, 0x8e, 0x0d, 0xd6, 0x8b, 0x9f, 0x08,
	0x16, 0x0e, 0x69, 0x2c, 0x96, 0x9c, 0xdd, 0x71, 0x46, 0x55, 0xb1, 0x15, 0x74, 0x4f, 0x78, 0xbb,
	0x92, 0x1d, 0xa8, 0x25, 0x9b, 0xde, 0x27, 0x6b, 0x59, 0xb2, 0xe5, 0x56, 0x65, 0x38, 0x3a, 0x18,
	0xa9, 0x55, 0xcc, 0x18, 0x63, 0x34, 0xa1, 0xc2, 0x42, 0x6f, 0xb2, 0x96, 0x38, 0x5a, 0x6e, 0x99,
	0x85, 0xde, 0x48, 0x89, 0xa9, 0x55, 0xde, 0x8b, 0xe3, 0xab, 0x9f, 0x22, 0x34, 0x37, 0xc3, 0xbe,
	0x6f, 0x97, 0x83, 0x37, 0xd0, 0xd8, 0x73, 0x42, 0x83, 0x1c, 0xaf, 0xc8, 0x46, 0x92, 0xc7, 0xa8,
	0xe1, 0x25, 0xd4, 0x15, 0x35, 0xd4, 0xc9, 0x11, 0x53, 0xdb, 0x20, 0x39, 0xa4, 0x1a, 0xde, 0x42,
	0x33, 0x83, 0x0f, 0x4d, 0x92, 0x47, 0x6c, 0xb7, 0xc9, 0x09, 0xc2, 0x8e, 0x86, 0xaf, 0x60, 0xe4,
	0x68, 0x61, 0x97, 0x9c, 0xa3, 0x6b, 0xdb, 0xe4, 0x2c, 0x5c, 0x47, 0xbb, 0x28, 0xdc, 0xd7, 0x3e,
	0x2a, 0xf2, 0x51, 0x7e, 0x56, 0xe5, 0xe7, 0xfa, 0x37, 0x00, 0x00, 0xff, 0xff, 0x8d, 0xa9, 0xdf,
	0x5a, 0xb6, 0x02, 0x00, 0x00,
}
