// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/streamer.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type StartStreamingRequest struct {
	MediaId     string `protobuf:"bytes,1,opt,name=media_id,json=mediaId" json:"media_id,omitempty"`
	GstPipeline string `protobuf:"bytes,2,opt,name=gst_pipeline,json=gstPipeline" json:"gst_pipeline,omitempty"`
	// Use 0 to allocate random port
	Port int32 `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
}

func (m *StartStreamingRequest) Reset()                    { *m = StartStreamingRequest{} }
func (m *StartStreamingRequest) String() string            { return proto1.CompactTextString(m) }
func (*StartStreamingRequest) ProtoMessage()               {}
func (*StartStreamingRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *StartStreamingRequest) GetMediaId() string {
	if m != nil {
		return m.MediaId
	}
	return ""
}

func (m *StartStreamingRequest) GetGstPipeline() string {
	if m != nil {
		return m.GstPipeline
	}
	return ""
}

func (m *StartStreamingRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type StartStreamingResponse struct {
	ListenPort uint32 `protobuf:"varint,1,opt,name=listen_port,json=listenPort" json:"listen_port,omitempty"`
}

func (m *StartStreamingResponse) Reset()                    { *m = StartStreamingResponse{} }
func (m *StartStreamingResponse) String() string            { return proto1.CompactTextString(m) }
func (*StartStreamingResponse) ProtoMessage()               {}
func (*StartStreamingResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *StartStreamingResponse) GetListenPort() uint32 {
	if m != nil {
		return m.ListenPort
	}
	return 0
}

func init() {
	proto1.RegisterType((*StartStreamingRequest)(nil), "StartStreamingRequest")
	proto1.RegisterType((*StartStreamingResponse)(nil), "StartStreamingResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Streamer service

type StreamerClient interface {
	StartStreaming(ctx context.Context, in *StartStreamingRequest, opts ...grpc.CallOption) (*StartStreamingResponse, error)
}

type streamerClient struct {
	cc *grpc.ClientConn
}

func NewStreamerClient(cc *grpc.ClientConn) StreamerClient {
	return &streamerClient{cc}
}

func (c *streamerClient) StartStreaming(ctx context.Context, in *StartStreamingRequest, opts ...grpc.CallOption) (*StartStreamingResponse, error) {
	out := new(StartStreamingResponse)
	err := grpc.Invoke(ctx, "/Streamer/StartStreaming", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Streamer service

type StreamerServer interface {
	StartStreaming(context.Context, *StartStreamingRequest) (*StartStreamingResponse, error)
}

func RegisterStreamerServer(s *grpc.Server, srv StreamerServer) {
	s.RegisterService(&_Streamer_serviceDesc, srv)
}

func _Streamer_StartStreaming_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartStreamingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamerServer).StartStreaming(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Streamer/StartStreaming",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamerServer).StartStreaming(ctx, req.(*StartStreamingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Streamer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Streamer",
	HandlerType: (*StreamerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartStreaming",
			Handler:    _Streamer_StartStreaming_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/streamer.proto",
}

func init() { proto1.RegisterFile("proto/streamer.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x2e, 0x29, 0x4a, 0x4d, 0xcc, 0x4d, 0x2d, 0xd2, 0x03, 0x73, 0x95, 0x32, 0xb9,
	0x44, 0x83, 0x4b, 0x12, 0x8b, 0x4a, 0x82, 0xc1, 0xc2, 0x99, 0x79, 0xe9, 0x41, 0xa9, 0x85, 0xa5,
	0xa9, 0xc5, 0x25, 0x42, 0x92, 0x5c, 0x1c, 0xb9, 0xa9, 0x29, 0x99, 0x89, 0xf1, 0x99, 0x29, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0xec, 0x60, 0xbe, 0x67, 0x8a, 0x90, 0x22, 0x17, 0x4f, 0x7a,
	0x71, 0x49, 0x7c, 0x41, 0x66, 0x41, 0x6a, 0x4e, 0x66, 0x5e, 0xaa, 0x04, 0x13, 0x58, 0x9a, 0x3b,
	0xbd, 0xb8, 0x24, 0x00, 0x2a, 0x24, 0x24, 0xc4, 0xc5, 0x52, 0x90, 0x5f, 0x54, 0x22, 0xc1, 0xac,
	0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0x66, 0x2b, 0x59, 0x72, 0x89, 0xa1, 0x5b, 0x55, 0x5c, 0x90, 0x9f,
	0x57, 0x9c, 0x2a, 0x24, 0xcf, 0xc5, 0x9d, 0x93, 0x59, 0x5c, 0x92, 0x9a, 0x17, 0x0f, 0xd6, 0x04,
	0xb2, 0x8e, 0x37, 0x88, 0x0b, 0x22, 0x14, 0x90, 0x5f, 0x54, 0x62, 0xe4, 0xcf, 0xc5, 0x11, 0x0c,
	0x75, 0xb7, 0x90, 0x33, 0x17, 0x1f, 0xaa, 0x31, 0x42, 0x62, 0x7a, 0x58, 0xbd, 0x20, 0x25, 0xae,
	0x87, 0xdd, 0x3e, 0x25, 0x06, 0x27, 0xf6, 0x28, 0x56, 0xb0, 0xff, 0x93, 0xd8, 0xc0, 0x94, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x0b, 0x83, 0x68, 0x1e, 0x01, 0x00, 0x00,
}
